### PR TITLE
python 3 compatibility

### PR DESCRIPTION
**Pull request by fredhope2000**
Couple of syntax fixes so that this package supports Python 3.

Versioned to 0.3.0 but I could also see just doing a 0.0.1 bump. I'll leave that up to the authors.

### CODE REVIEW

**Comment by fredhope2000** [comment]
@sgillies

**Comment by fredhope2000** [comment]
May want to squash this as it has a couple commits (a change plus an undo of the change, for the PR) to the readme that are specific to the fork.

**Review by sgillies — APPROVED** [review]
@fredhope2000 great, thank you!

**Comment by sgillies** [comment]
@fredhope2000 I might change the version to 1.0.0 after I merge this, because I feel like the package is more or less finished. How do you feel about that?

I can probably get a release out this weekend.

**Comment by fredhope2000** [comment]
@sgillies sure sounds good, whatever you think is best. We've been using the package for some time for kml parsing but not too extensively. Thanks for the quick approval!

**Pull request merged**
